# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Haoer Blog    #博客名
subtitle: 雪忆, 如雪般单纯, 冷静思考.  #博客副标题
description:          #网站描述, 用于爬虫抓取的关键词
author: kevin    #作者名称
email: angularfang@gmail.com  #作者邮箱
language: zh-Hans       #网页编码,简体中文

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://haoer.com   #用于绑定域名, 其他的不需要配置
root: /
permalink: :year/:month/:day/:title/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
permalink_defaults:

# Directory
source_dir: source  
public_dir: public

# Writing, 设置生成博文的默认格式,不修改
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives
#Archives 默认值为2,修改为1,Archives页面就只会列出标题,而非全文
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 1
category: 1
tag: 1

# Server服务器设置, 不修改
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
server_ip: localhost
logger: false
logger_format: dev

# Date / Time format 日期格式
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMM D YYYY
time_format: H:mm:ss

# Pagination 分页, 设置每页显示多少篇博文
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Disqus  disqus评论,  与多说类似, 国内一般使用多说
disqus_shortname: 

# Extensions
## Plugins: https://github.com/hexojs/hexo/wiki/Plugins
## Themes: https://github.com/hexojs/hexo/wiki/Themes
theme: next    #主题设置
exclude_generator:

#百度统计
baidu_analytics: e8604faa2ef85feb8ae0b4438ffe8eb3

# Deployment  站点部署到github要配置这里, 非常重要
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git    #部署类型, 本文使用Github
  repository: https://github.com/kevincefang/kevincefang.github.io.git  #部署的仓库的SSH
  branch: master   #部署分支,一般使用master主分支
  message: just static